### ISSUE TITLE
Recycle memory

### ISSUE THREAD

**Issue by jklontz** [biometrics/likely#10]
Change `likely_allocate` and `likely_free` to recycle memory buffers. Make sure the implementation is thread safe, but ideally lock free.

**Comment by sklum** [comment]
I'll try and start here.

**Comment by jklontz** [comment]
Good pick, this one should be relatively simple and very self contained. I'm curious how much time is spent in `malloc` and `free` -- it is often quite substantial, so this could offer good speedup.

**Comment by jklontz** [comment]
I'm taking on #14 next, which will impact the solution for this I think.

**Comment by sklum** [comment]
Although I am watching the mailing list with great interest, I haven't been able to dive in to anything meaningful.  Hopefully that will change within the coming weeks, but feel free to take over this issue and I can join with a different one when I have more free time.
