### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by jklontz** [biometrics/likely#29]
Support ternary (?:) conditionals

**Comment by jklontz** [comment]
@JordanCheney Perhaps you'd like to take this on after thresholding?

I think this is can happen in a few stages:

1) Comparisons: lt(lhs,rhs). lt = less than. also add functions for gt, lte, gte
2) Conditionals: if(condition,then,else). this would basically be a generalization of the current thresholding functionality.

**Comment by jklontz** [comment]
Oh and `eq` and `neq`

**Comment by JordanCheney** [comment]
Do conditionals still need to be implemented? Just want to make sure no one else completed this while I was on my hiatus :)

**Comment by jklontz** [comment]
Yeah, what I'm looking for is a translation of the LLVM `select` instruction as a Likely intrinsic, then implement threshold in terms of comparison and select

**Comment by jklontz** [comment]
Finished in 46b57832b9d4f3d05e49be77f011116445573364
