### ISSUE TITLE
Can't build latest code

### ISSUE THREAD

**Issue by JordanCheney** [biometrics/likely#31]
Really excited to see casting in action :) but I can't compile the code :( any ideas on this error?

git submodule update
fatal: reference is not a tree: 5b9f06563e24b79821cf40b5fbd537e5318d9ead
Unable to checkout '5b9f06563e24b79821cf40b5fbd537e5318d9ead' in submodule path 'llvm'

**Comment by jklontz** [comment]
Should be fixed in 5c15b4186f2a445b1f9757b612d2e78d187c1441

This was actually a problem upstream :)
http://llvm.1065342.n5.nabble.com/Announcement-LLVM-3-4-Has-Branched-td63549.html
