### ISSUE TITLE
Greyscale conversion

### ISSUE THREAD

**Issue by JordanCheney** [biometrics/likely#33]
Implementing image conversion from BGR to greyscale. I'm not sure where this would fall in the pipeline of current work, and it may require some changes to the current allocation of the channels of the dst matrix.

**Comment by jklontz** [comment]
This falls into the 0.2 release window. Basically we need to figure out how to implement reductions first. I'm hoping the syntax will look something like:

multiply({0.299,0.587,0.114}) .. sum(channels)

`..` will be the function piping operator which I hope to introduce later today.

**Comment by jklontz** [comment]
Implemented in 0507d54f41c50e4544de7919646588003bbc1119
