### ISSUE TITLE
Linux Arch build: "file INSTALL cannot find"

### ISSUE THREAD

**Issue by anatol** [biometrics/likely#37]
Hi,

I am trying to build HEAD on Linux Arch
$ git clone https://github.com/biometrics/likely.git
$ cd likely
$ git submodule init
$ git submodule update
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make install

and "make install" fails:

[ 90%] Built target LLVMCodeGen
[ 90%] Built target LLVMJIT
[ 92%] Built target LLVMAsmPrinter
[ 95%] Built target LLVMSelectionDAG
[ 95%] Built target LLVMMCJIT
[100%] Built target LLVMX86CodeGen
Scanning dependencies of target likely
[100%] Building CXX object src/CMakeFiles/likely.dir/__/likely_standard_library.cpp.o
Linking CXX static library liblikely.a
[100%] Built target likely
Linking CXX executable ../bin/benchmark
[100%] Built target benchmark
Install the project...
-- Install configuration: "Release"
-- Installing: /home/anatol/sources/archpackages/liblikely-git/pkg/liblikely-git/usr/include/likely_aux.h
-- Installing: /home/anatol/sources/archpackages/liblikely-git/pkg/liblikely-git/usr/include/likely_script.h
-- Installing: /home/anatol/sources/archpackages/liblikely-git/pkg/liblikely-git/usr/lib/liblikely.a
-- Installing: /home/anatol/sources/archpackages/liblikely-git/pkg/liblikely-git/usr/include/likely.h
CMake Error at src/cmake_install.cmake:52 (FILE):
  file INSTALL cannot find
  "/home/anatol/sources/archpackages/liblikely-git/src/likely/src/share".
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)

Makefile:65: recipe for target 'install' failed
make: **\* [install] Error 1

**Comment by jklontz** [comment]
oops referenced wrong issue
