### ISSUE TITLE
Build process should provide shared libraries as well

### ISSUE THREAD

**Issue by anatol** [biometrics/likely#38]
'make install' currently builds only static library. Some distros (like linux arch) prefer shared libraries. It would be very useful if 'make' build/install shared libraries as well.

Somewhat related http://stackoverflow.com/questions/12899582/cmake-how-can-i-build-a-shared-and-a-static-library-without-recompiling-the-sou

**Comment by anatol** [comment]
And 'benchmark' binary should be linked dynamically.

**Comment by jklontz** [comment]
Rebuild with `BUILD_SHARED_LIBS=ON`, will update the README

**Comment by jklontz** [comment]
There's probably an expectation that shared libraries is the default, re-opening this ticket until then.

**Comment by jklontz** [comment]
Fixed in 25869ea4fe4608f4a6cb0d0522041a7a5262db45

**Comment by anatol** [comment]
A lot of applications prefer to ship both static and shared libraries. I think it is what autotools does by default.

**Comment by jklontz** [comment]
Can you provide an example of popular application that ships with both shared and static libs, and why they do so? I haven't encountered this convention before.

**Comment by anatol** [comment]
> Can you provide an example of popular application that ships with both shared and static libs

Any projects that is built with autotools does it. Here is the first project I opened on my computer URCU (http://lttng.org/urcu), 'make install' install following files:

liburcu.a                liburcu-cds.a            liburcu-common.la        liburcu-mb.la            liburcu-qsbr.so          liburcu-signal.so.3
liburcu-bp.a             liburcu-cds.la           liburcu-common.so        liburcu-mb.so            liburcu-qsbr.so.3        liburcu-signal.so.3.0.0
liburcu-bp.la            liburcu-cds.so           liburcu-common.so.3      liburcu-mb.so.3          liburcu-qsbr.so.3.0.0    liburcu.so
liburcu-bp.so            liburcu-cds.so.3         liburcu-common.so.3.0.0  liburcu-mb.so.3.0.0      liburcu-signal.a         liburcu.so.3
liburcu-bp.so.3          liburcu-cds.so.3.0.0     liburcu.la               liburcu-qsbr.a           liburcu-signal.la        liburcu.so.3.0.0
liburcu-bp.so.3.0.0      liburcu-common.a 

> and why they do so

To allow users use the library both with static and dynamic linking. Different users have different preferences. e.g. on Linux Arch it is highly recommended to use shared libs.

I do not know how difficult to make it with CMake. In any case this is relatively minor issue for me - I can use compile-time option as I need only shared lib.
