### ISSUE TITLE
Compile liblikely against system libraries

### ISSUE THREAD

**Issue by anatol** [biometrics/likely#39]
I see that the project pulls as a submodules a set of dependencies, some of them are heavy (e.g. llvm). Is there any specific reason for this? Would it be possible just use system libraries? Many *nix systems already have llvm/opencv and other libs installed. This will solve several issues:

1) will make build much faster - no need to compile llvm
2) liblikely.so is compiled against local version of llvm but at runtime it will be linked against system llvm shared library. There might be chance that these 2 versions of llvm(/opencv/..) have different ABI and thus the library be broken.

**Comment by jklontz** [comment]
Completely agree. The current system is designed to be as simple as possible to compile under all operating systems, including ones with terrible or non-existant package managers (Windows). Having said that, if the libraries already exist on the system, we should use them by default. This is on my todo list, but isn't a priority at the moment. Would welcome a PR to address this issue.
