### ISSUE TITLE
'test' project created by CMake not building on Windows

### ISSUE THREAD

**Issue by krk** [biometrics/likely#48]
CUSTOMBUILD : LLVM error : Program used external function 'sinf' which could not be resolved!

**Comment by jklontz** [comment]
Can you confirm MSVC 2013? That symbol should exist in their latest C runtime ...

**Comment by krk** [comment]
Platform toolset: Visual Studio 2013 (v120)

**Comment by jklontz** [comment]
K thanks, will have to get back to you on this one :)

**Comment by krk** [comment]
lenna.tiff path is dependent on what we choose as the build directory in CMake configurator. With the correct path it is working, though it does not detect that an image has 0px width and height.

**Comment by jklontz** [comment]
Works for me, make sure you're loading the 2013 C library at runtime?
