### ISSUE TITLE
Handle escaped characters in tokenization

### ISSUE THREAD

**Issue by jklontz** [biometrics/likely#53]
@sklum or @JordanCheney - Here's an easy one if you want to get your feet wet.

Likely currently doesn't recognize escaped characters:

```
# Currently:
$ likely '"my\nstring"'
my\nstring

# Desired:
$ likely '"my\nstring"'
my
string
```

To fix this, the `tokenize` function in `frontend.cpp` needs to be improved to recognize [Standard Escape Sequences](http://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences). No need to implement `\nnn` and `\xhh`. I think the right place to add this logic is just before `likely_ast token = likely_new_atom(&str[begin], i-begin);`.

A complete implementation of this feature should also describe the functionality in `library/standard.ll` and add a few test cases to `src/CMakeLists.txt`

**Comment by sklum** [comment]
dibs

**Comment by JordanCheney** [comment]
so fast! I call next one

**Comment by sklum** [comment]
we should work on it together. /hug

**Comment by sklum** [comment]
@jklontz Has this been taken care of or can I still start here?

**Comment by jklontz** [comment]
start here

**Comment by jklontz** [comment]
For a moment I thought `unescape` might be a standard library function. It seems that it's not, but I did come across a nice reference implementation:
http://www.opensource.apple.com/source/postfix/postfix-229/postfix/src/util/unescape.c

**Comment by sklum** [comment]
awesome.  my goal is to start this today.

**Comment by jklontz** [comment]
Decided this was better off in the backend than during tokenization.
