### ISSUE TITLE
Caffe model translation

### ISSUE THREAD

**Issue by Jerryg6j3** [biometrics/likely#61]
Hi, is there a neural network Caffe model translation example? A MNIST caffe model translator of some kind?

**Comment by jklontz** [comment]
We have a working closed-source implementation of what you're describing. If you have commercial interest in this please let me know. We don't have plans to open source it for the time being.

**Comment by Jerryg6j3** [comment]
I see. I'm just working on my thesis project, not really going commercial right now. Thanks for your response!
