### ISSUE TITLE
Smarter versions of `likely_hash_to_string` and `likely_string_to_hash`

### ISSUE THREAD

**Issue by jklontz** [biometrics/likely#8]
`likely_hash_to_string` should print out a human-understandable string under all circumstances. `likely_string_to_hash` should then also be updated correspondingly.

**Comment by JordanCheney** [comment]
I think my latest commit fixes this issue but see if you like the new format of likely_string_to_hash() because it now has optional bool inputs which I am not sure I like. Let me know if you can think of a better way to go about it!

**Comment by jklontz** [comment]
This is close to what I want would see, but not exactly right. I want the string to be as short as possible, with the presence/absence of single characters indicating boolean field values. Then `likely_hash_to_string` can check for the presence of these characters in the string, instead of taking boolean function arguments.

**Comment by JordanCheney** [comment]
Ok, if I am understanding correctly, would a good solution be "i32PH" indicating a i32 hash with parallel and heterogeneous set to true while "i32O" would be an i32 hash with just the owner set to true?

**Comment by jklontz** [comment]
Precisely. Play around with upper and lowercase letters to see what reads
the best too please!

**Comment by jklontz** [comment]
And if you can start sending bite-size pull requests, I'll start merging them. Don't want your branches to build up with too many changes :)

**Comment by jklontz** [comment]
Fixed in #11
